kind: Service
apiVersion: v1
metadata:
  name: say-my-name-backend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    role: backend
    app: say-my-name